---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts, email, email notifications, console notifications, filter, filtering 
summary: 您可以設定NetApp Workload Factory，在發生某些類型的事件時向某個人或其他應用程式發送通知。 
---
= 配置NetApp Workload Factory 通知
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
您可以設定 NetApp Workload Factory 通知服務，使其將通知以警報形式傳送至 NetApp Console、帳戶關聯的任何電子郵件地址或 Amazon SNS 主題。如果您已部署 Console 代理或鏈接，則以警報形式傳送的通知將顯示在 NetApp Console 中。當 Workload Factory 將通知發佈到 Amazon SNS 主題時，該主題的訂閱者（例如使用者或其他應用程式）將透過為該主題配置的端點（例如電子郵件或簡訊）接收通知。



== 通知類型和訊息

Workload Factory 針對下列事件發送通知：

[cols="6*"]
|===
| 活動 | 說明 | 通知類型 | 嚴重性 | 工作負載 | 資源類型 


| 您帳戶中的某些資料庫執行個體架構不佳 | 您的帳戶中的所有 Microsoft SQL Server 執行個體均已針對架構問題進行分析。此事件的描述給出了架構良好的實例和未最佳化的實例的數量。從工作負載工廠控制台查看資料庫清單中精心設計的狀態結果和建議。 | 架構完善 | 建議 | 資料庫 | Microsoft SQL Server 實例 


| Microsoft SQL Server/PostgreSQL 伺服器部署成功 | Microsoft SQL Server 或 PostgreSQL 主機部署成功。更多信息，請參考作業監控。 | 部署 | 成功 | 資料庫 | FSx for ONTAP，資料庫主機 


| Microsoft SQL Server/PostgreSQL 伺服器部署失敗 | Microsoft SQL Server 或 PostgreSQL 主機部署失敗。更多信息，請參考作業監控。 | 部署 | 錯誤 | 資料庫 | FSx for ONTAP，資料庫主機 


| 複製關係創建失敗 | SnapMirror複製關係建立失敗。欲了解更多信息，請訪問 Tracker。 | 複製 | 批判的 | 常規存儲 | 適用於ONTAP的 FSx 


| FSx for ONTAP建立失敗 | FSx for ONTAP檔案系統建立過程失敗。欲了解更多信息，請訪問 Tracker。 | FSx for ONTAP檔案系統操作 | 批判的 | 常規存儲 | 適用於ONTAP的 FSx 


| 自動增加 SSD 容量或 inode 成功 | 在最近的自動容量管理更新期間，FSx for ONTAP檔案系統成功增加了 SSD 容量或磁碟區 inode。欲了解更多信息，請訪問 Tracker。 | 容量管理 | 成功 | 常規存儲 | FSx for ONTAP文件 


| 自動增加 SSD 容量或 inode 失敗 | 在最近的自動容量管理更新期間，FSx for ONTAP檔案系統未能增加 SSD 容量或磁碟區 inode。欲了解更多信息，請訪問 Tracker。 | 容量管理 | 批判的 | 常規存儲 | FSx for ONTAP檔案系統 


| 偵測到 FSx for ONTAP問題 | 所有 FSx for ONTAP檔案系統均已針對架構問題進行了分析。掃描偵測到一個或多個問題。有關更多信息，請查看 Workload Factory 控制台中存儲儀表板的精心設計的分析。 | 精心設計的分析 | 建議 | 常規存儲 | FSx for ONTAP檔案系統 


| FSx for ONTAP的自動容量管理事件 | FSx for ONTAP檔案系統的 SSD 效能層級已達到警告閾值容量/百分比總和。 | 容量管理 | 警告 | 常規存儲 | FSx for ONTAP檔案系統 


| FSx for ONTAP的自動 inode 管理事件 | ONTAP磁碟區的 FSx inode 計數達到警告閾值計數/百分比總數。 | 容量管理 | 警告 | 常規存儲 | FSx for ONTAP檔案系統 


| 在 FSx for ONTAP 檔案系統中偵測到可疑磁碟區活動 | NetApp 具備人工智慧的自主勒索軟體防護（ARP/AI）偵測到可疑的磁碟區活動。 | 勒索軟體防護 | 批判的 | 常規存儲 | FSx for ONTAP檔案系統 


| 偵測到延遲臨界值突破 | FSx for ONTAP 叢集中的一個或多個磁碟區超過了延遲閾值。 | 效能監控 | 警告 | EDA | FSx for ONTAP檔案系統 


| 每月成本報告 | 每月帳戶費用匯總，顯示支出趨勢、異常變化以及適用於 FSx for ONTAP 檔案系統的最佳節省機會。 | 成本報告 | 建議 | 常規存儲 | FSx for ONTAP檔案系統 


| 複製延遲 | 複寫作業所需時間超出預期。 | 複製 | 批判的 | 常規存儲 | FSx for ONTAP檔案系統 
|===


== 配置工作負載工廠通知

您可以使用 NetApp Console 或 Workload Factory 主控台來設定 Workload Factory 通知。

接收通知的選項包括：



=== NetApp控制台

* *通知*：設定 Workload Factory 以傳送顯示在 NetApp Console 鈴鐺圖示下的通知。
* *電子郵件*：在 NetApp Console 啟用電子郵件通知，無需設定 Amazon SNS，即可將通知發送到與帳戶關聯的任何電子郵件地址。
* *Amazon SNS*：設定 Workload Factory 以傳送通知至 Amazon SNS 主題。




=== 工作負載工廠控制台

* *電子郵件*：在 Workload Factory Console 中啟用電子郵件通知，即可接收傳送至與該帳戶關聯的任何電子郵件地址的通知，而無需設定 Amazon SNS。
* *Amazon SNS*：使用 Workload Factory 主控台設定 Workload Factory 以向 Amazon SNS 主題發送通知。



IMPORTANT: 當你在 NetApp Console 中設定通知時，NetApp Console 會接管通知傳送的管理權限，並且 Workload Factory console 的通知選項會被停用並以唯讀模式顯示。工具提示會顯示通知是由 NetApp Console 管理。之後你只能從 NetApp Console 管理通知。

.開始之前
以下先決條件僅適用於設定 Amazon SNS 通知時：

* 您需要使用 Amazon SNS 主控台或 AWS CLI 配置 Amazon SNS 並建立 Amazon SNS 主題。
* 請注意，Workload Factory 支援 *標準* 主題類型。這種類型的主題不能確保通知按照收到的順序發送給訂閱者，因此如果您有關鍵或緊急通知，請考慮這一點。


[role="tabbed-block"]
====
.從NetApp控制台配置通知
--
.步驟
. 登入link:https://console.netapp.com["NetApp控制台"^]。
. 從NetApp控制台選單中，選擇 *Workloads*、*Administration*，然後選擇 *Notifications setup*。
. 在「通知」設定頁面上，啟用下列一或多種通知類型：
+
.. *NetApp Console 通知*：選擇*啟用 NetApp Console 通知*以設定 Workload Factory 在 NetApp Console 中傳送通知。
.. *電子郵件通知*：選取 *啟用電子郵件通知*，將 Workload Factory 設定為傳送通知至與該帳戶相關聯的任何電子郵件地址。
.. *Amazon SNS 通知*：選取*啟用 SNS 通知*，然後依照指示從 Amazon SNS 主控台設定 Amazon SNS。
+
建立主題後，複製主題 ARN 並將其輸入到 *通知設定* 頁面上的 *SNS 主題 ARN* 欄位中。



. 透過發送測試通知驗證配置後，選擇*套用*。


--
.從 Workload Factory 控制台設定通知
--
.步驟
. 登入link:https://console.workloads.netapp.com["工作負載工廠控制台"^]。
. 從 Workload Factory 控制台選單中，選擇 *Workloads*、*Administration*，然後選擇 *Notifications setup*。
. 啟用以下一種或多種通知類型：
+
** *電子郵件通知*：選取 *啟用電子郵件通知*。與該帳戶相關聯的任何電子郵件地址都會以唯讀模式顯示。
** *Amazon SNS 通知*：選取*啟用 SNS 通知*，然後依照指示從 Amazon SNS 主控台設定 Amazon SNS。
+
透過發送測試通知驗證配置後，選擇*套用*。





--
====


== 訂閱 Amazon SNS 主題

配置 Workload Factory 向主題發送通知後，請依照 https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["說明"]在 Amazon SNS 文件中訂閱主題，以便您可以接收來自 Workload Factory 的通知。



== 篩選通知

您可以透過對通知套用篩選器，減少不必要的通知流量，並針對特定使用者推播特定類型的通知。您可以使用 Amazon SNS 策略來管理 SNS 通知，也可以在 NetApp Console 中使用通知設定來實現這一點。



=== 篩選 Amazon SNS 通知

當您訂閱 Amazon SNS 主題時，您會在預設情況下收到發佈到該主題的所有通知。如果您只想接收主題的特定通知，則可以使用篩選策略來控制接收哪些通知。過濾策略使 Amazon SNS 僅向訂閱者發送符合過濾策略的通知。

您可以依照以下條件篩選 Amazon SNS 通知：

[cols="3*"]
|===
| 說明 | 過濾策略欄位名稱 | 可能值 


| 資源類型 | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| 工作負載 | `workload` | `WLMDB` 


| 優先事項 | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| 通知類型 | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.步驟
. 在 Amazon SNS 控制台中，編輯 SNS 主題的訂閱詳細資訊。
. 在*訂閱過濾策略*區域，選擇按*訊息屬性*進行過濾。
. 啟用*訂閱過濾策略*選項。
. 在 *JSON 編輯器* 框中輸入 JSON 過濾策略。
+
例如，以下 JSON 過濾策略接受來自 Microsoft SQL Server 資源的與 WLMDB 工作負載相關的通知，優先順序為成功或錯誤，並提供有關 Well-architected 狀態的詳細資訊：

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. 選擇“儲存變更”。


有關過濾策略的其他範例，請參閱 https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Amazon SNS 範例篩選策略"^]。

有關創建過濾策略的更多信息，請參閱 https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["Amazon SNS 文件"^]。



=== 在 NetApp Console 中篩選通知

您可以使用 NetApp Console 通知設定，依嚴重性層級（例如 Critical、Info 或 Warning）篩選您在 Console 中收到的通知。

有關在控制台中過濾通知的更多信息，請參閱 https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#filter-notifications["NetApp控制台文檔"^]。
