---
settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 設定與管理文件
    url: "/index.html"
  - title: 版本資訊
    entries:
    - title: 新增功能
      url: "/whats-new.html"
  - title: 開始使用
    entries:
    - title: 瞭解基礎知識
      entries:
      - title: 工作負載工廠概覽
        url: "/workload-factory-overview.html"
      - title: 作業模式
        url: "/operational-modes.html"
    - title: 快速入門
      url: "/quick-start.html"
    - title: 報名參加 Workload Factory
      url: "/sign-up-saas.html"
    - title: 新增 AWS 認證
      url: "/add-credentials.html"
    - title: 接下來您可以做什麼
      url: "/whats-next.html"
  - title: 管理 Workload Factory
    entries:
    - title: 登入 Workload Factory
      url: "/log-in.html"
    - title: 使用 Codebox 自動化工作
      entries:
      - title: 瞭解 CodeBox
        url: "/codebox-automation.html"
      - title: 使用 Codebox 產生程式碼
        url: "/use-codebox.html"
    - title: 移除認證資料
      url: "/manage-credentials.html"
  - title: 知識與支援
    entries:
    - title: 註冊以取得支援
      url: "/support-registration.html"
    - title: 取得協助
      url: "/get-help.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: BlueXP Workload Factory for AWS
  repo: workload-family
