---
settings:
  name: Setup and administration
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: 設定與管理文件
    url: "/index.html"
  - title: 版本資訊
    entries:
    - title: 新增功能
      url: "/whats-new.html"
  - title: 開始使用
    entries:
    - title: 瞭解基礎知識
      entries:
      - title: 瞭解 BlueXP  工作負載工廠
        url: "/workload-factory-overview.html"
      - title: 作業模式
        url: "/operational-modes.html"
      - title: 主控台體驗
        url: "/console-experiences.html"
      - title: 權限
        url: "/permissions-reference.html"
    - title: 快速入門
      url: "/quick-start.html"
    - title: 註冊至工作負載工廠
      url: "/sign-up-saas.html"
    - title: 新增 AWS 認證
      url: "/add-credentials.html"
    - title: 使用工作負載工廠優化工作負載
      url: "/whats-next.html"
  - title: 管理工作負載工廠
    entries:
    - title: 登入工作負載工廠
      url: "/log-in.html"
    - title: 管理服務帳戶
      url: "/manage-service-accounts.html"
    - title: 設定通知
      url: "/configure-notifications.html"
    - title: 使用 Codebox 自動化工作
      entries:
      - title: 瞭解 CodeBox
        url: "/codebox-automation.html"
      - title: 使用 Codebox 產生程式碼
        url: "/use-codebox.html"
    - title: 使用 CloudShell
      url: "/use-cloudshell.html"
    - title: 移除認證資料
      url: "/manage-credentials.html"
  - title: 知識與支援
    entries:
    - title: 註冊以取得支援
      url: "/support-registration.html"
    - title: 取得協助
      url: "/get-help.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
