---
sidebar: sidebar 
permalink: well-architected-workloads.html 
keywords: well-architected, best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: Workload Factory 會掃描工作負載配置的可靠性、安全性、卓越營運、成本優化和效能效率，並提供見解和建議，幫助您實現卓越營運。 
---
= 使用 NetApp Workload Factory 建構和運行架構良好的工作負載
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory 是 NetApp 管理套件，適用於 Amazon FSx for NetApp ONTAP，可協助您維護和執行符合 AWS Well-Architected Framework 的可靠、安全、高效且經濟的工作負載配置。Workload Factory 提供每日工作負載分析、建議和自動修復，以促進工作負載的健康運作。透過自動化此流程，Workload Factory 可最大限度地減少人為錯誤，並確保工作負載管理的一致性。



== 工作原理

Workload Factory 每日分析您在 Amazon FSx for NetApp ONTAP 檔案系統部署上執行的工作負載。此分析提供架構完善的狀態資訊、洞察分析和建議。

每日分析完成後，部署的配置會在「架構完善」儀表板中顯示為「已最佳化」或「未最佳化」。您將看到總優化得分、按類別劃分的配置問題以及配置問題和建議清單。您可以查看針對配置問題的建議。有些問題可以由工作負載工廠自動修復，而有些問題則需要人工幹預。在這種情況下，工作負載工廠會提供詳細的說明來幫助您實施建議的變更。

您可以忽略不適用於您環境的配置分析。這樣可以避免不必要的警報和不準確的優化結果。當您忽略某個設定分析時，Workload Factory 不會將該配置計入總最佳化得分。



== 為什麼這很重要

Workload Factory 將最佳實踐應用於大型儲存、資料庫和 VMware 環境，透過持續評估與建議洞察和修復措施相結合。在 Workload Factory 主控台中套用的自動化修復可減少人為錯誤、確保統一管理，並維護工作負載基礎架構的效能和可靠性。



== 開始使用 Workload Factory 來偵測和修復工作負載配置錯誤

若要開始使用 Workload Factory、請註冊、新增認證資料並建立連線、以使用 Amazon FSx for NetApp ONTAP 來管理 AWS 資源並最佳化工作負載。

link:https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["快速入門"]



== 相關資訊

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["為ONTAP檔案系統實作架構良好的 FSx"^]
* link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["實作架構良好的資料庫工作負載"^]
* link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["實作架構良好的 EVS 配置"^]

